/**
 * Generates from public/assets/dtii/tile_list_v1.7.txt:
 *  - public/assets/dtii/atlas.json   (Phaser 3 atlas: every named frame)
 *  - src/game/dtii-frames.ts         (checked-in rect table for game code & tooling)
 * Run: npx vite-node scripts/generate-dtii-atlas.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';

const listPath = 'public/assets/dtii/tile_list_v1.7.txt';
const frames: Record<string, { frame: { x: number; y: number; w: number; h: number } }> = {};
const rects: Record<string, [number, number, number, number]> = {};

for (const line of readFileSync(listPath, 'utf8').split(/\r?\n/)) {
  const m = line.trim().match(/^(\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)$/);
  if (!m) continue;
  const [, name, x, y, w, h] = m;
  frames[name] = { frame: { x: +x, y: +y, w: +w, h: +h } };
  rects[name] = [+x, +y, +w, +h];
}

writeFileSync(
  'public/assets/dtii/atlas.json',
  JSON.stringify({ frames, meta: { image: 'dungeon_sheet.png' } }),
);

const names = Object.keys(rects).sort();
const body = names.map((n) => `  ${JSON.stringify(n)}: [${rects[n].join(', ')}],`).join('\n');
writeFileSync(
  'src/game/dtii-frames.ts',
  `// GENERATED by scripts/generate-dtii-atlas.ts from tile_list_v1.7 — do not edit by hand.
export const SHEET_COLS = 32; // 512px sheet / 16px grid

export const DTII_FRAMES = {
${body}
} as const;

export type DtiiFrameName = keyof typeof DTII_FRAMES;
`,
);
console.log(`atlas.json + dtii-frames.ts written (${names.length} frames)`);
