# Measures the opaque-art bounding box of each blob template cell's 16x16
# footprint (the lower half of the 16x32 piece) in walls_high.png and emits
# src/game/dtii-wall-insets.ts. Colliders derive from these insets so walls
# collide where they are VISIBLE — transparent ground margins stay walkable.
# Run: pwsh scripts/generate-wall-insets.ps1   (npm run assets:insets)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$sheetPath = (Resolve-Path (Join-Path $PSScriptRoot '..\public\assets\dtii\walls_high.png')).Path
$outPath = Join-Path $PSScriptRoot '..\src\game\dtii-wall-insets.ts'
$bmp = [System.Drawing.Bitmap]::new($sheetPath)

$lines = @()
for ($cell = 0; $cell -lt 48; $cell++) {
  if ($cell -eq 22) { continue } # the template's blank cell
  $sx = ($cell % 12) * 16
  $sy = [Math]::Floor($cell / 12) * 32
  $left = 16; $right = -1; $top = 16; $bottom = -1
  for ($y = 0; $y -lt 16; $y++) {
    for ($x = 0; $x -lt 16; $x++) {
      if ($bmp.GetPixel($sx + $x, $sy + 16 + $y).A -gt 128) {
        if ($x -lt $left) { $left = $x }
        if ($x -gt $right) { $right = $x }
        if ($y -lt $top) { $top = $y }
        if ($y -gt $bottom) { $bottom = $y }
      }
    }
  }
  if ($right -lt 0) {
    Write-Warning "cell $cell has no opaque footprint pixels; falling back to full cell"
    $left = 0; $right = 15; $top = 0; $bottom = 15
  }
  $lines += ('  ' + $cell + ': [' + $left + ', ' + $top + ', ' + (15 - $right) + ', ' + (15 - $bottom) + '],')
}
$bmp.Dispose()

$header = @(
  '// GENERATED by scripts/generate-wall-insets.ps1 (npm run assets:insets) — do not edit.',
  '/**',
  ' * Opaque-art bounding insets [left, top, right, bottom] of each blob template',
  " * cell's 16x16 footprint (the lower half of the 16x32 walls_high piece).",
  ' * Colliders derive from these so walls collide where they are VISIBLE and the',
  " * art's transparent ground margins stay walkable.",
  ' */',
  'export const WALL_CELL_INSETS: Readonly<Record<number, readonly [number, number, number, number]>> = {'
)
$footer = @('};', '')
Set-Content -Path $outPath -Value ($header + $lines + $footer) -Encoding utf8
Write-Output "wrote $outPath ($($lines.Count) cells)"
